# -------------------------------
# DYNAMIC MULTI-DATASOURCE (Examples)
# -------------------------------
app.swagger.enabled=true
app.request-logging.enabled=true
app.cors.allowed-origin-patterns=*

# app.datasource.enabled=true
# app.datasource.primary=core
#
# app.datasource.connections.core.url=jdbc:postgresql://localhost:5432/dev_core_db
# app.datasource.connections.core.username=postgres
# app.datasource.connections.core.password=postgres
# app.datasource.connections.core.driver-class-name=org.postgresql.Driver
# app.datasource.connections.core.maximum-pool-size=10
# app.datasource.connections.core.minimum-idle=2
#
# app.datasource.connections.audit.url=jdbc:sqlserver://localhost:1433;databaseName=dev_audit_db;encrypt=false;trustServerCertificate=true
# app.datasource.connections.audit.username=sa
# app.datasource.connections.audit.password=YourStrong@Passw0rd
# app.datasource.connections.audit.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# app.datasource.connections.audit.maximum-pool-size=10
# app.datasource.connections.audit.minimum-idle=2
#
# app.datasource.connections.analytics.url=jdbc:postgresql://localhost:5432/dev_analytics_db
# app.datasource.connections.analytics.username=postgres
# app.datasource.connections.analytics.password=postgres
# app.datasource.connections.analytics.driver-class-name=org.postgresql.Driver
# app.datasource.connections.analytics.maximum-pool-size=8
# app.datasource.connections.analytics.minimum-idle=1